### ISSUE TITLE
Remove BIP32 path lock for generic wallet app

### ISSUE THREAD

**Issue by destrys** [LedgerHQ/ledger-app-eth#16]
I’d like to request that the BIP32 path lock for the generic Ethereum wallet app be removed or made less restrictive.  In particular, we want to be able to export information for `m/45'` and any children `m/45'/*` (to arbitrary depth).

There are several reasons I am requesting this change:

1. The existing Bitcoin app does not have any similar BIP32 path restrictions and we are already reliant on this functionality.  This proposed change would make the Ethereum app more consistent with the Bitcoin app.

2. We use the `m/45'/*` BIP32 space for multisig so that our users do not need to expose the `m/44'/*` space used by their single-sig wallets when working with us. This standard was proposed in BIP45, and is used by Electrum.

3. To generate addresses, we need to export xpubs at `m/45'/*`.  Since the Ledger API only allows exporting public keys, to get the xpub at (say) `m/45'/60'`, we need to be able to export the public key for both `m/45'/60'` *and* `m/45'` (just `m/45'/*` would be insufficient for us).

So the minimum request for our use-case is to open up `m/45'/*`, though for consistency with the bitcoin ledger app and other hardware wallets, removing the BIP32 path lock entirely would be ideal.

We suspect the required change may be as simple as changing the `Makefile` to remove the path restriction.  In particular, changing
```
ifeq ($(CHAIN),ethereum)
#APP_LOAD_PARAMS += --path "44'"
...
```

to 

```
ifeq ($(CHAIN),ethereum)
#APP_LOAD_PARAMS += --path "44'"
#APP_LOAD_PARAMS += --path "45'"
...

**Comment by destrys** [comment]
There are several reasons I am requesting this enhancement.

1. We have developed a multisig ethereum contract. For multisig, we use the m/45'/ bip32 branch so that single-sig addresses at common paths do not need to be exposed. This was proposed in BIP45, and used by Electrum, though neither are accepted standards.

2. Constructing an extended public key. With the current implementation, you must pull the public key and chain code for the path of interest and the public key of the parent of that path. This is possible with the current production bitcoin app, but it would be convenient to not ask users to use the bitcoin app to construct an xpub that will be used for ethereum.

So the minimum request for our use-case is to open up m/45', though for consistency with the bitcoin ledger app and other hardware wallets, removing the BIP32 path lock entirely would be ideal.

**Comment by clementperon** [comment]
The path are now locked in 1.5.x, I have open a PR to fix this issue : 
https://github.com/LedgerHQ/ledger-app-eth/pull/56

**Comment by destrys** [comment]
Pretty sure #56 closes this.
