### ISSUE TITLE
Breaking changes between v1.0.24 and v1.1.4

### ISSUE THREAD

**Issue by ChaceHunter** [LedgerHQ/ledger-app-eth#36]
The recent update to the Ethereum Ledger app introduced some breaking changes for our users trying to stake in the SpankBank.

v1.0.24 still works for users staking SPANK on the SpankBank (https://bank.spankchain.com), users that are using v1.1.4 are not able to stake even with Contract Data 'On' and Display Data both 'On' or 'Off'.

Any guidance would be appreciated.
If necessary, here is our web3 repo for the SpankBank: https://github.com/SpankChain/spankbank-web3

**Comment by fbonetti** [comment]
@mslipper Similar issue: https://github.com/LedgerHQ/ledgerjs/issues/214

Also, Ledger freezes when signing a large transaction. I suspect it has something to do with "Display data", but the setting can't be turned off without throwing an error when signing. Our users didn't have this issue until after the recent firmware update.

**Comment by btchip** [comment]
This should be fixed in ETH application version 1.1.6 - can you please recheck ?

**Comment by ChaceHunter** [comment]
During this time MetaMask integrated Ledger support so we switched to allowing only that for users wishing to stake in the SpankBank. Considering this, there's not really a way to test it so I will now close this issue.
