### ISSUE TITLE
Ledger device: Invalid data received(0x6a80)

### ISSUE THREAD

**Issue by youfoundron** [LedgerHQ/ledger-app-eth#43]
Contract data -> YES
Display data -> YES

When an Ethereum transaction's input data is not sufficiently padded it rejects the transaction.

For example, a transaction with the input data `0x123` would fail, while a transaction with the input data `0x123000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000` would succeed.

In both cases, when display data -> NO
The transaction is accepted

Also related https://github.com/kvhnuke/etherwallet/issues/2044

**Comment by thanhnguyennguyen** [comment]
I got same issue
@youfoundron any updates or workaround ? 

{code}
{to: "0x0000000000000000000000000000000000000088", data: "0x6dd7d8ea000000000000000000000000fc5571921c6d3672e13b58ea23dea534f2b35fa0", value: 10000000000000000000, gasPrice: 2500, gas: 1000000}data: "0x6dd7d8ea000000000000000000000000fc5571921c6d3672e13b58ea23dea534f2b35fa0"gas: 1000000gasPrice: 2500to: "0x0000000000000000000000000000000000000088"value: 10000000000000000000__proto__: Object
app.js?9fee:364 f84e808209c4830f4240940000000000000000000000000000000000000088888ac7230489e80000a46dd7d8ea000000000000000000000000fc5571921c6d3672e13b58ea23dea534f2b35fa0598080
app.js?9fee:367 teststste
Voting.vue?47f1:326 
{code}

**Comment by bwheeler96** [comment]
I'm having this issue currently

**Comment by satoshi-ninja** [comment]
#metoo

**Comment by bwheeler96** [comment]
Full firmware upgrade of the ledger and reinstall of Ethereum app fixed it

**Comment by youfoundron** [comment]
Closing, it seems this is fixed in firmware version 1.5.5

**Comment by theoturner** [comment]
For sending custom tokens, enable contract data in the Ethereum app on-device.

This error will also show up if you don't have contract data enabled when trying to send custom tokens, even with firmware 1.5.5 and Ethereum wallet 1.2.

**Comment by Moejoe90** [comment]
I'm getting this error even when firmare 1.5.5 and Ethereum Wallet 1.2.4
I have contract data enabled and display data enabled also 
everything works fine when display data is disabled

**Comment by k06a** [comment]
Having this problem with Ledger firmware 1.5.5 and Callisto app 1.1.9. Both "contract data" and "display data" options enabled.

**Comment by HauRuck** [comment]
I'm on firmware 1.5.5 and Ethereum Wallet 1.2.4 and when interacting with https://cdp.makerdao.com (withdrawing eth) I get this error.

**Comment by boczeratul** [comment]
Getting the same error for some input data

**Comment by ianaz** [comment]
Same error with 1.5.5 with Metamask + Chrome & Brave too

**Comment by sweetpotatoz** [comment]
Ledger Nano S firmware 1.5.5 wit Ethereum App 1.2.7
Google Chrome Version 74.0.3729.131 (Official Build) (64-bit)
having error like this
-32603 Error: TransportStatusError: Ledger device: Invalid data received (0x6a80)"}

**Comment by nielsiano** [comment]
Latest Brave/Chrome with 1.5.5, same error here.

**Comment by cellard0or** [comment]
Same for me on MyCrypto App and 1.5.5 firmware.

**Comment by drajay9628** [comment]
HI STILL I HAVE THIS PROBLEM

I CHANGED 3 DIVICES 
UODATE ALL MY SYSTEM & LEDGER LIVE BUT 

PROBLEM NOT SOLVED

**Comment by youfoundron** [comment]
@drajay9628 

chill out a sec.
start from your base assumptions.

ledger live is the desktop _software_; you need to update the _device firmware_.
here is a video tutorial: https://support.ledger.com/hc/en-us/articles/360002731113-Update-Ledger-Nano-S-firmware

good luck.

**Comment by Bird-NZ** [comment]
@drajay9628 "For sending custom tokens, enable contract data in the Ethereum app on-device." 
This worked for me. What it means specifically is on the ledger hardware device itself open the ETH app and in setting set "contract data" to ALLOWED.

**Comment by mrbluecoat** [comment]
@Bird-NZ that worked for me - thanks

**Comment by leachy14** [comment]
> @drajay9628 "For sending custom tokens, enable contract data in the Ethereum app on-device."
> This worked for me. What it means specifically is on the ledger hardware device itself open the ETH app and in setting set "contract data" to ALLOWED.

Worked for me on uniswap, thanks

**Comment by Ficus86** [comment]
> @drajay9628 "For sending custom tokens, enable contract data in the Ethereum app on-device."
> This worked for me. What it means specifically is on the ledger hardware device itself open the ETH app and in setting set "contract data" to ALLOWED.

thanks a lot, this solved the issue on my side as well!

**Comment by Gian-Lorenzo** [comment]
> @drajay9628 "For sending custom tokens, enable contract data in the Ethereum app on-device."
> This worked for me. What it means specifically is on the ledger hardware device itself open the ETH app and in setting set "contract data" to ALLOWED.

Yep, this worked for me, thanks so much!

**Comment by pavlovdog** [comment]
Yep, confirmed - the problem has been caused by the disabled contract data. Check the instruction on the [Ledger docs](https://support.ledger.com/hc/en-us/articles/115005200009-Set-up-and-use-MyEtherWallet).

![image](https://user-images.githubusercontent.com/5871170/97215464-86aeaf00-17d5-11eb-98e6-af0dac9084e3.png)
