### ISSUE TITLE
ETC app connection issue on different "devices" (0x6804)

### ISSUE THREAD

**Issue by rumatoest** [LedgerHQ/ledger-app-eth#55]
Probably it is a good idea to make another bug report here, that is related to https://github.com/LedgerHQ/ledger-live-desktop/issues/1753#issuecomment-456178534

Ledger Nano S
Wallets: Ledger Live 12.7, 1.30, 1.32, MyEtherWallet, MyCrypto.AppImage
Platform and version: Windows 10 64bit and Ubuntu 18.04 64bit
ETC and ETH apps v1.1.8
Secure element 1.5.5 MCU 1.7

I'm not able to use ETC app on different platforms and wallets.
In all cases I'm not able to establish any connection with ETC app. If there is any error explanation available I can see an error code 0x6804 
Like: `Ledger device: UNKNOWN_ERROR (0x6804)`

**Comment by expathos** [comment]
I can't access either when trying to login using Network ILT net.iolite.io 

Invalid status 6804. Check to make sure the right application is selected ?

**Comment by clementperon** [comment]
Hi @rumatoest , sorry for the delay.

Yes you are right we don't review a lot Github issues for now. If you want a quick support please contact the dedicated support : https://support.ledger.com/hc/en-us.

If you want to directly contact devs we have a slack for that : https://ledger-dev.slack.com/

**Comment by rumatoest** [comment]
Considering my last conversation with support I can definitely say that they completely incompetent in questions related to software bugs.
